import Head from 'next/head'
import React, { useEffect, useState } from 'react'



export interface characterObject {
    id: number
    name: string
    status: string
    species: string
    type: string
    gender: string
    origin: Origin
    location: Location
    image: string
    episode: string[]
    url: string
    created: string
}

export type arrayOfCharacters = characterObject[] | null


function CSRExample() {




    const [data, setData] = useState<arrayOfCharacters>(null)
    console.log(data)
    useEffect(() => {
        /* this is used to cancel the fetch when you repeat */
        let controller = new AbortController()
        const signal = controller.signal
        const getData = async () => {

            try {
                const response = await fetch("https://rickandmortyapi.com/api/character", { signal })
                if (response.ok) {
                    const result = await response.json()
                    console.log(result)
                    setData(result["results"])
                }
            }


            catch (error) {

            }
        }
        getData()

        return (() => {
            controller.abort();
        })



    }, [])

    return (
        <>
            <Head>
                <title>This is the start of the project</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>CSRExample</div>
            <div className='entryContainer'>
                {data && data.map((entry) => {
                    return (<div className='entryDiv'>{entry.name}</div>)

                })}
            </div>
        </>
    )
}

export default CSRExample