import { GetServerSideProps } from 'next'
import Head from 'next/head'
import React from 'react'


export interface EpisodeData{
    info: Info
    results: Result[]
  }
  
  export interface Info {
    count: number
    pages: number
    next: string
    prev: any
  }
  
  export interface Result {
    id: number
    name: string
    type: string
    dimension: string
    residents: string[]
    url: string
    created: string
  }
  
interface SSGComponentProps{
    episodeData:EpisodeData
}



export const getServerSideProps:GetServerSideProps<SSGComponentProps>=async()=>{
    const urlLocation="https://rickandmortyapi.com/api/location"

    const response = await fetch(urlLocation)
    const results = await response.json()

    console.log(results)

    return {
        props:{
            episodeData: results
        }
    }

}

function SSGExample({episodeData}:SSGComponentProps) {
    console.log(episodeData)
    return (
        <>
            <Head>
                <title>This is the start of the project</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>SSGExample</div></>

    )
}

export default SSGExample